name: E2E on Chrome

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
     - name: Cypress run
       uses: cypress-io/github-action@v6
       with:
          build: npm run build
          start: npm start
          project: ./cypress/e2e/1-getting-started
          browser: chrome
           wait-on: "https://example.cypress.io/todo"